import { createServer } from 'node:http';
import { randomUUID } from 'node:crypto';
import { mkdir, writeFile, readFile, unlink } from 'node:fs/promises';
import { join, extname } from 'node:path';
import { JsonStore } from './store.js';
import { bearer, createToken, hashPassword, publicMember, tokenHash, verifyPassword } from './auth.js';
import { FileMailer, invitationEmail } from './mailer.js';

const json = (res, status, body) => { res.writeHead(status, { 'content-type': 'application/json; charset=utf-8' }); res.end(JSON.stringify(body)); };
const body = async req => { const chunks=[]; for await (const chunk of req) chunks.push(chunk); if (!chunks.length) return {}; try { return JSON.parse(Buffer.concat(chunks)); } catch { throw Object.assign(new Error('JSONの形式が不正です'), { status: 400 }); } };
const match = (pathname, pattern) => { const keys=[]; const regex=new RegExp(`^${pattern.replace(/:([A-Za-z]+)/g,(_,key)=>(keys.push(key),'([^/]+)'))}$`); const found=pathname.match(regex); return found ? Object.fromEntries(keys.map((key,index)=>[key,decodeURIComponent(found[index+1])])) : null; };
const required = (value, name) => { if (!value || (Array.isArray(value)&&!value.length)) throw Object.assign(new Error(`${name}は必須です`), { status: 422 }); };
const validPassword = value => { if (typeof value !== 'string' || value.length < 8) throw Object.assign(new Error('パスワードは8文字以上で入力してください'), { status: 422 }); };
const fileTypes={'.pdf':['application/pdf'],'.png':['image/png'],'.jpg':['image/jpeg'],'.jpeg':['image/jpeg'],'.xlsx':['application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'],'.xls':['application/vnd.ms-excel'],'.pptx':['application/vnd.openxmlformats-officedocument.presentationml.presentation'],'.ppt':['application/vnd.ms-powerpoint'],'.docx':['application/vnd.openxmlformats-officedocument.wordprocessingml.document'],'.doc':['application/msword']};
const validateFile=(name,mime,buffer)=>{const ext=extname(name).toLowerCase();if(!fileTypes[ext]?.includes(mime))throw Object.assign(new Error('対応していないファイル形式です'),{status:422});if(buffer.length>50*1024*1024)throw Object.assign(new Error('ファイルは50MB以下にしてください'),{status:413});if(ext==='.pdf'&&buffer.subarray(0,4).toString()!=='%PDF')throw Object.assign(new Error('PDFの内容が不正です'),{status:422});if(ext==='.png'&&buffer.subarray(1,4).toString()!=='PNG')throw Object.assign(new Error('PNGの内容が不正です'),{status:422});if(['.jpg','.jpeg'].includes(ext)&&(buffer[0]!==0xff||buffer[1]!==0xd8))throw Object.assign(new Error('JPEGの内容が不正です'),{status:422});return ext};


export async function runNotificationSweep(store, now = new Date()) {
  const nowMs=now.getTime();
  return store.update(db=>{
    let created=0;
    for(const task of db.tasks) {
      if(task.status==='done'||task.status==='completed') continue;
      const confirmed=new Set(task.confirmedByIds||[]);
      const ageMs=nowMs-new Date(task.createdAt).getTime();
      if(ageMs>=72*60*60*1000) for(const userId of task.assigneeIds||[]) if(!confirmed.has(userId)) {
        const dedupeKey=`task.confirmation.overdue:${task.id}:${userId}`;
        if(!db.notifications.some(n=>n.dedupeKey===dedupeKey)) { db.notifications.push({id:randomUUID(),userId,eventType:'task.confirmation.overdue',resourceType:'task',resourceId:task.id,title:'タスクが72時間確認されていません',dedupeKey,readAt:null,createdAt:now.toISOString()}); created++; }
      }
      if(task.dueAt) {
        const days=Math.ceil((new Date(task.dueAt).getTime()-nowMs)/(24*60*60*1000));
        if(days===3) for(const userId of task.assigneeIds||[]) {
          const dedupeKey=`task.deadline.three_days:${task.id}:${userId}`;
          if(!db.notifications.some(n=>n.dedupeKey===dedupeKey)) { db.notifications.push({id:randomUUID(),userId,eventType:'task.deadline.three_days',resourceType:'task',resourceId:task.id,title:'タスク期限の3日前です',dedupeKey,readAt:null,createdAt:now.toISOString()}); created++; }
        }
      }
    }
    return {created};
  });
}

export function createApi({ store = new JsonStore(process.env.DATA_FILE || 'data/database.json'), mailer = new FileMailer(process.env.MAILBOX_DIR || 'data/mailbox'), allowedOrigin = process.env.CORS_ORIGIN || '*' } = {}) {
  return createServer(async (req,res) => {
    res.setHeader('access-control-allow-origin', allowedOrigin); res.setHeader('access-control-allow-methods','GET,POST,PATCH,PUT,DELETE,OPTIONS'); res.setHeader('access-control-allow-headers','content-type,authorization,idempotency-key');
    if (req.method === 'OPTIONS') return res.writeHead(204).end();
    const url=new URL(req.url,'http://localhost'); const path=url.pathname;
    try {
      if (req.method==='GET' && path==='/health') return json(res,200,{status:'ok'});
      const currentSession=async()=>{const token=bearer(req);if(!token)return null;const db=await store.read();const session=db.sessions.find(item=>item.tokenHash===tokenHash(token)&&new Date(item.expiresAt)>new Date());if(!session)return null;const member=db.members.find(item=>item.id===session.userId);return member?{session,member}:null};
      const requireUser=async()=>{const auth=await currentSession();if(!auth)throw Object.assign(new Error('ログインが必要です'),{status:401});return auth};
      const requireAdmin=async()=>{const auth=await requireUser();if(auth.member.role!=='admin')throw Object.assign(new Error('管理者権限が必要です'),{status:403});return auth};
      if(req.method==='POST'&&path==='/v1/auth/bootstrap'){const input=await body(req);required(input.email,'email');validPassword(input.password);const member=await store.update(async db=>{if(db.members.length)throw Object.assign(new Error('初期管理者は登録済みです'),{status:409});const item={id:randomUUID(),email:input.email.toLowerCase(),name:input.name||'管理者',company:input.company||'',council:input.council||'',title:input.title||'',role:'admin',status:'active',passwordHash:await hashPassword(input.password),createdAt:new Date().toISOString()};db.members.push(item);return item});return json(res,201,{member:publicMember(member)});}
      if(req.method==='POST'&&path==='/v1/auth/login'){const input=await body(req);const db=await store.read();const member=db.members.find(item=>item.email?.toLowerCase()===String(input.email||'').toLowerCase()&&item.status!=='deleted');if(!member||!await verifyPassword(input.password,member.passwordHash))throw Object.assign(new Error('メールアドレスまたはパスワードが正しくありません'),{status:401});const token=createToken();const session={id:randomUUID(),userId:member.id,tokenHash:tokenHash(token),expiresAt:new Date(Date.now()+30*86400000).toISOString(),createdAt:new Date().toISOString()};await store.update(data=>data.sessions.push(session));return json(res,200,{token,expiresAt:session.expiresAt,member:publicMember(member)});}
      if(req.method==='GET'&&path==='/v1/auth/session'){const auth=await requireUser();return json(res,200,{member:publicMember(auth.member),expiresAt:auth.session.expiresAt});}
      if(req.method==='POST'&&path==='/v1/auth/logout'){const token=bearer(req);if(token)await store.update(db=>{db.sessions=db.sessions.filter(item=>item.tokenHash!==tokenHash(token))});res.writeHead(204);return res.end();}
      if(req.method==='PATCH'&&path==='/v1/users/me'){const auth=await requireUser();const input=await body(req);const member=await store.update(db=>{const found=db.members.find(item=>item.id===auth.member.id);if(input.email&&db.members.some(item=>item.id!==found.id&&item.email?.toLowerCase()===input.email.toLowerCase()))throw Object.assign(new Error('このメールアドレスは使用済みです'),{status:409});for(const key of ['name','email','company','council','title'])if(input[key]!==undefined)found[key]=key==='email'?input[key].toLowerCase():input[key];return found});return json(res,200,{member:publicMember(member)});}
      if(req.method==='PUT'&&path==='/v1/users/me/password'){const auth=await requireUser();const input=await body(req);validPassword(input.newPassword);if(!await verifyPassword(input.currentPassword,auth.member.passwordHash))throw Object.assign(new Error('現在のパスワードが正しくありません'),{status:422});const encoded=await hashPassword(input.newPassword);await store.update(db=>{db.members.find(item=>item.id===auth.member.id).passwordHash=encoded;db.sessions=db.sessions.filter(item=>item.userId!==auth.member.id)});res.writeHead(204);return res.end();}
      let invitationParams=match(path,'/v1/invitations/:token');
      if(invitationParams&&req.method==='GET'){const db=await store.read();const invite=db.invitations.find(item=>item.tokenHash===tokenHash(invitationParams.token)&&!item.acceptedAt&&new Date(item.expiresAt)>new Date());if(!invite)throw Object.assign(new Error('招待リンクが無効または期限切れです'),{status:404});return json(res,200,{email:invite.email,role:invite.role,expiresAt:invite.expiresAt});}
      if(invitationParams&&req.method==='POST'){const input=await body(req);required(input.name,'name');validPassword(input.password);const member=await store.update(async db=>{const invite=db.invitations.find(item=>item.tokenHash===tokenHash(invitationParams.token)&&!item.acceptedAt&&new Date(item.expiresAt)>new Date());if(!invite)throw Object.assign(new Error('招待リンクが無効または期限切れです'),{status:404});const item={id:randomUUID(),email:invite.email,name:input.name,company:invite.company||'',council:invite.council||'',title:invite.title||'',role:invite.role,status:'active',passwordHash:await hashPassword(input.password),createdAt:new Date().toISOString()};db.members=db.members.filter(existing=>existing.invitationId!==invite.id);db.members.push(item);invite.acceptedAt=new Date().toISOString();return item});return json(res,201,{member:publicMember(member)});}

      if (req.method==='GET' && path==='/v1/projects') { const db=await store.read(); const q=(url.searchParams.get('q')||'').toLowerCase(); const status=url.searchParams.get('status'); return json(res,200,{items:db.projects.filter(p=>(!q||`${p.name}${p.ownerName||''}`.toLowerCase().includes(q))&&(!status||p.status===status))}); }
      if (req.method==='POST' && path==='/v1/projects') { const input=await body(req); required(input.name,'name'); const item={id:randomUUID(),name:input.name,description:input.description||'',status:input.status||'企画中',ownerId:input.ownerId||null,ownerName:input.ownerName||'',council:input.council||'',dueAt:input.dueAt||null,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}; await store.update(db=>db.projects.push(item)); return json(res,201,item); }
      let projectParams=match(path,'/v1/projects/:projectId');
      if(projectParams&&req.method==='PATCH'){await requireUser();const input=await body(req);const project=await store.update(db=>{const found=db.projects.find(item=>item.id===projectParams.projectId);if(!found)throw Object.assign(new Error('案件が見つかりません'),{status:404});for(const key of ['name','description','status','ownerId','ownerName','council','dueAt'])if(input[key]!==undefined)found[key]=input[key];found.updatedAt=new Date().toISOString();return found});return json(res,200,project);}
      let params=match(path,'/v1/projects/:projectId/files');
      if(params&&req.method==='GET'){const db=await store.read();return json(res,200,{items:db.files.filter(file=>file.projectId===params.projectId)});}
      if(params&&req.method==='POST'){const auth=await requireUser();const input=await body(req);required(input.name,'name');required(input.mimeType,'mimeType');required(input.base64,'base64');const buffer=Buffer.from(input.base64,'base64');const ext=validateFile(input.name,input.mimeType,buffer);const id=randomUUID();const storageKey=`${id}${ext}`;const uploadDir=process.env.UPLOAD_DIR||'data/uploads';await mkdir(uploadDir,{recursive:true});await writeFile(join(uploadDir,storageKey),buffer,{flag:'wx'});const item={id,projectId:params.projectId,storageKey,originalName:input.name,mimeType:input.mimeType,sizeBytes:buffer.length,uploadedBy:auth.member.id,createdAt:new Date().toISOString()};await store.update(db=>db.files.push(item));return json(res,201,item);}
      let fileParams=match(path,'/v1/files/:fileId');
      if(fileParams&&req.method==='GET'){await requireUser();const db=await store.read();const file=db.files.find(item=>item.id===fileParams.fileId);if(!file)throw Object.assign(new Error('ファイルが見つかりません'),{status:404});const content=await readFile(join(process.env.UPLOAD_DIR||'data/uploads',file.storageKey));res.writeHead(200,{'content-type':file.mimeType,'content-disposition':`attachment; filename*=UTF-8''${encodeURIComponent(file.originalName)}`});return res.end(content);}
      if(fileParams&&req.method==='DELETE'){await requireUser();let removed;await store.update(db=>{const index=db.files.findIndex(item=>item.id===fileParams.fileId);if(index<0)throw Object.assign(new Error('ファイルが見つかりません'),{status:404});removed=db.files.splice(index,1)[0]});await unlink(join(process.env.UPLOAD_DIR||'data/uploads',removed.storageKey)).catch(()=>{});res.writeHead(204);return res.end();}
      params=match(path,'/v1/projects/:projectId/tasks');
      if (params && req.method==='GET') { const db=await store.read(); return json(res,200,{items:db.tasks.filter(t=>t.projectId===params.projectId)}); }
      if (params && req.method==='POST') { const input=await body(req); required(input.title,'title'); required(input.assigneeIds,'assigneeIds'); const task={id:randomUUID(),projectId:params.projectId,title:input.title,description:input.description||'',status:'open',dueAt:input.dueAt||null,assigneeIds:[...new Set(input.assigneeIds)],confirmedByIds:[],lastActivityAt:new Date().toISOString(),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()}; await store.update(db=>{db.tasks.push(task); for(const userId of task.assigneeIds) db.notifications.push({id:randomUUID(),userId,eventType:'task.assigned',resourceType:'task',resourceId:task.id,title:'タスクが割り当てられました',readAt:null,createdAt:new Date().toISOString()});}); return json(res,201,task); }
      params=match(path,'/v1/tasks/:taskId');
      if (params && req.method==='PATCH') { const input=await body(req); const updated=await store.update(db=>{const task=db.tasks.find(t=>t.id===params.taskId); if(!task) throw Object.assign(new Error('タスクが見つかりません'),{status:404}); Object.assign(task,input,{updatedAt:new Date().toISOString(),lastActivityAt:new Date().toISOString()}); return task;}); return json(res,200,updated); }
      params=match(path,'/v1/tasks/:taskId/confirmations');
      if (params && req.method==='POST') { const input=await body(req); required(input.userId,'userId'); const task=await store.update(db=>{const found=db.tasks.find(t=>t.id===params.taskId); if(!found) throw Object.assign(new Error('タスクが見つかりません'),{status:404}); if(!found.assigneeIds.includes(input.userId)) throw Object.assign(new Error('担当者だけが確認できます'),{status:403}); found.confirmedByIds=[...new Set([...(found.confirmedByIds||[]),input.userId])]; found.lastActivityAt=new Date().toISOString(); found.updatedAt=found.lastActivityAt; return found;}); return json(res,200,task); }
      params=match(path,'/v1/tasks/:taskId/comments');
      if (params && req.method==='GET') { const db=await store.read(); return json(res,200,{items:db.comments.filter(c=>c.taskId===params.taskId)}); }
      if (params && req.method==='POST') { const input=await body(req); required(input.body,'body'); const comment={id:randomUUID(),taskId:params.taskId,authorId:input.authorId,body:input.body,mentionedUserIds:[...new Set(input.mentionedUserIds||[])],createdAt:new Date().toISOString()}; await store.update(db=>{if(!db.tasks.some(t=>t.id===params.taskId)) throw Object.assign(new Error('タスクが見つかりません'),{status:404}); db.comments.push(comment); const task=db.tasks.find(t=>t.id===params.taskId); task.lastActivityAt=comment.createdAt; for(const userId of comment.mentionedUserIds) db.notifications.push({id:randomUUID(),userId,eventType:'comment.mentioned',resourceType:'task',resourceId:task.id,title:'コメントでメンションされました',readAt:null,createdAt:comment.createdAt});}); return json(res,201,comment); }
      if (req.method==='GET' && path==='/v1/members') { await requireUser();const db=await store.read(); return json(res,200,{items:db.members.map(publicMember)}); }
      params=match(path,'/v1/members/:memberId');
      if (params && req.method==='PATCH') { await requireAdmin();const input=await body(req);if(!['admin','member'].includes(input.role))throw Object.assign(new Error('roleが不正です'),{status:422});const member=await store.update(db=>{const found=db.members.find(m=>m.id===params.memberId);if(!found)throw Object.assign(new Error('メンバーが見つかりません'),{status:404});found.role=input.role;return found});return json(res,200,{member:publicMember(member)});}
      if (params && req.method==='DELETE') { await requireAdmin();await store.update(db=>{const index=db.members.findIndex(m=>m.id===params.memberId); if(index<0) throw Object.assign(new Error('メンバーが見つかりません'),{status:404}); db.members.splice(index,1); for(const task of db.tasks) task.assigneeIds=(task.assigneeIds||[]).filter(id=>id!==params.memberId);}); res.writeHead(204); return res.end(); }
      if (req.method==='POST' && path==='/v1/invitations') { const auth=await requireAdmin();const input=await body(req); required(input.email,'email');const token=createToken();const invitation={id:randomUUID(),email:input.email.toLowerCase(),company:input.company||'',council:input.council||'',title:input.title||'',role:input.role==='admin'?'admin':'member',tokenHash:tokenHash(token),status:'pending',expiresAt:new Date(Date.now()+7*86400000).toISOString(),createdAt:new Date().toISOString()};await store.update(db=>{if(db.members.some(member=>member.email?.toLowerCase()===invitation.email&&member.status==='active'))throw Object.assign(new Error('このメールアドレスは登録済みです'),{status:409});db.invitations.push(invitation);db.members.push({id:randomUUID(),invitationId:invitation.id,email:invitation.email,name:input.name||'招待中',company:invitation.company,council:invitation.council,title:invitation.title,role:invitation.role,status:'招待中'})});const inviteUrl=`${process.env.APP_URL||'http://localhost:5173'}?invite=${encodeURIComponent(token)}`;const delivery=await mailer.send(invitationEmail({email:invitation.email,inviterName:auth.member.name,inviteUrl}));return json(res,201,{id:invitation.id,email:invitation.email,expiresAt:invitation.expiresAt,delivery}); }
      if (req.method==='GET' && path==='/v1/notifications') { const db=await store.read(); const userId=url.searchParams.get('userId'); return json(res,200,{items:db.notifications.filter(n=>!userId||n.userId===userId)}); }
      params=match(path,'/v1/users/:userId/notification-preferences');
      if (params && req.method==='GET') { const db=await store.read(); return json(res,200,{items:db.notificationPreferences.filter(p=>p.userId===params.userId)}); }
      if (params && req.method==='PUT') { const input=await body(req); required(input.preferences,'preferences'); const items=input.preferences.map(p=>({userId:params.userId,channel:p.channel,eventType:p.eventType,enabled:Boolean(p.enabled)})); await store.update(db=>{db.notificationPreferences=db.notificationPreferences.filter(p=>p.userId!==params.userId).concat(items)}); return json(res,200,{items}); }
      return json(res,404,{error:'NOT_FOUND',message:'エンドポイントが見つかりません'});
    } catch (error) { return json(res,error.status||500,{error:error.status===422?'VALIDATION_ERROR':'REQUEST_ERROR',message:error.message}); }
  });
}
